"use client";

import useDashboard from "@/hooks/useDashboard";

export default function AIExportReport() {
  const { rows, columnMapping } = useDashboard();

  function download(
    content: string,
    filename: string,
    type: string
  ) {
    const blob = new Blob([content], {
      type,
    });

    const url = URL.createObjectURL(blob);

    const link = document.createElement("a");

    link.href = url;

    link.download = filename;

    link.click();

    URL.revokeObjectURL(url);
  }

  function exportCSV() {
    if (!rows.length) return;

    const headers = Object.keys(rows[0]);

    const csv = [
      headers.join(","),

      ...rows.map((row) =>
        headers
          .map(
            (header) =>
              `"${String(
                row[header] ?? ""
              ).replace(/"/g, '""')}"`
          )
          .join(",")
      ),
    ].join("\n");

    download(
      csv,
      "leadpilot-data.csv",
      "text/csv"
    );
  }

  function exportJSON() {
    if (!rows.length) return;

    download(
      JSON.stringify(rows, null, 2),
      "leadpilot-data.json",
      "application/json"
    );
  }

  function exportSummary() {
    if (!rows.length) return;

    const revenueColumn =
      columnMapping["Revenue"];

    const statusColumn =
      columnMapping["Status"];

    const sourceColumn =
      columnMapping["Source"];

    let totalRevenue = 0;

    let converted = 0;

    const sourceCount: Record<
      string,
      number
    > = {};

    rows.forEach((row) => {
      if (revenueColumn) {
        const value = Number(
          String(
            row[revenueColumn] ?? ""
          ).replace(/[^\d.-]/g, "")
        );

        if (!isNaN(value)) {
          totalRevenue += value;
        }
      }

      if (statusColumn) {
        const status = String(
          row[statusColumn] ?? ""
        ).toLowerCase();

        if (
          status.includes("won") ||
          status.includes("converted") ||
          status.includes("closed")
        ) {
          converted++;
        }
      }

      if (sourceColumn) {
        const source = String(
          row[sourceColumn] ?? "Unknown"
        );

        sourceCount[source] =
          (sourceCount[source] || 0) + 1;
      }
    });

    const topSource =
      Object.entries(sourceCount).sort(
        (a, b) => b[1] - a[1]
      )[0]?.[0] ?? "N/A";

    const report = `
===============================
      LEADPILOT AI REPORT
===============================

Generated:
${new Date().toLocaleString()}

--------------------------------
Dataset Summary
--------------------------------

Total Leads:
${rows.length}

Total Revenue:
₹${totalRevenue.toLocaleString()}

Average Revenue:
₹${(
      totalRevenue /
      Math.max(rows.length, 1)
    ).toFixed(2)}

Conversion Rate:
${(
      (converted /
        Math.max(rows.length, 1)) *
      100
    ).toFixed(1)}%

Top Lead Source:
${topSource}

Rows Analysed:
${rows.length}

Columns:
${Object.keys(rows[0]).length}

--------------------------------

Generated by LeadPilot AI

`;

    download(
      report,
      "LeadPilot-AI-Report.txt",
      "text/plain"
    );
  }

  return (
    <section className="rounded-2xl border border-slate-800 bg-slate-900 p-6">
      <h2 className="mb-3 text-3xl font-bold">
        AI Export Report
      </h2>

      <p className="mb-8 text-slate-400">
        Export your dataset or generate an
        AI summary report.
      </p>

      <div className="grid gap-4 md:grid-cols-3">
        <button
          onClick={exportCSV}
          disabled={!rows.length}
          className="rounded-xl bg-blue-600 px-6 py-3 font-semibold hover:bg-blue-700 disabled:opacity-50"
        >
          Export CSV
        </button>

        <button
          onClick={exportJSON}
          disabled={!rows.length}
          className="rounded-xl bg-green-600 px-6 py-3 font-semibold hover:bg-green-700 disabled:opacity-50"
        >
          Export JSON
        </button>

        <button
          onClick={exportSummary}
          disabled={!rows.length}
          className="rounded-xl bg-purple-600 px-6 py-3 font-semibold hover:bg-purple-700 disabled:opacity-50"
        >
          Export AI Report
        </button>
      </div>

      {!rows.length && (
        <p className="mt-6 text-sm text-slate-500">
          Upload a CSV file to enable export
          options.
        </p>
      )}
    </section>
  );
}